name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Flutter version
      run: flutter --version
    - name: Install dependencies
      run: flutter pub get
    - name: Format check
      run: |
        flutter format --set-exit-if-changed .
    - name: Analyze
      run: flutter analyze
    - name: Run tests
      run: flutter test --no-pub
    - name: Build APK (debug)
      run: flutter build apk --debug